### ISSUE TITLE
Auto regenerating auth and other security issue concerns

### ISSUE THREAD

**Issue by Sighyu** [danieltoth-sys/SpotifyPlayer#1]
You can send a GET request to https://open.spotify.com/get_access_token?reason=transport&productType=web_player
with the following cookies from open.spotify.com using your browser to get them
sp_t
sp_dc
sp_key

Also leaving your auth in the repo allows anyone else to use it before it expires just a heads up (malicious users might add 10000 rick roll songs to your playlist)

**Comment by danieltoth-sys** [comment]
Thanks for the help!

And I never push the active oauth code. Only when it expires.
